config/routes.rb
TrendytaPinTab::Application.routes.draw do
  resources :categories
  
  resources :products

  post 'tab/like'

  get 'tab/index'
  
  get 'session/login'
  match '/login' => 'session#login'
  match '/signin' => 'session#signin'
    
  get 'charts/index'
  match '/charts' => 'charts#index'
  
  match '/like' => 'tab#like'
  
  match "/tab" => "tab#index"
  match "/tab_app" => "tab#app_redirect"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  belongs_to :product
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  establish_connection "live_trendyta"
  set_table_name "collection"
  
  attr_accessible :collection_name, :collection_slogan, :collection_url, :created_at, :created_by, :description, :designer_id, :image, :in_review, :margin_auth, :offer_ends, :offer_starts, :profit_margin_id, :published, :status, :thumb, :updated_at, :updated_by
  def readonly?
    return true
  end
  def readonly!
  end
end

app/models/collection_like.rb
class CollectionLike < ActiveRecord::Base
  attr_accessible :collection_description, :collection_image, :collection_name, :collection_slogan, :id_collection, :id_user, :like, :status
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :cookie, :product_id
  validates_uniqueness_of :cookie, :scope => :product_id
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  attr_accessible :category_id, :image, :name
  has_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    @likes = Like.count(:group => "product_id")
    @likes.each do |l|
      puts l[1]
      puts Product.find(l[0]).name
      l[2] = Product.find(l[0]).name
    end
    render "index", :layout => "chart"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    puts @products.inspect
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def login
    @user = User.new
  end
  
  def signin
    @user = User.new(params[:user])
    @user.password = Digest::SHA1.hexdigest(@user.password)
    @user.name = @user.name.downcase
    user = User.where("name = '#{@user.name}' AND password = '#{@user.password}'")
    if user.empty?
      @user.error = ""
    else
      session[:user] = user
    end
  end
end

app/controllers/tab_controller.rb
require 'open-uri'
require 'base64'
require 'json'

class TabController < ApplicationController
  def index
    usrcookie = cookies[:sessionkey]
    if usrcookie.nil?
      usrcookie = cookies[:sessionkey] = Digest::SHA1.hexdigest(Time.now.to_time.to_i.to_s)
    end
    @products = Product.all()
  end
  
  def app_redirect
    render 'redirect_app' , :layout => 'redirect'
  end
  
  def like
    usrcookie = cookies[:sessionkey]
    like = Like.new
    like.cookie = usrcookie
    like.product_id = params["id"]
    puts like.inspect
    like.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoriaproductos_helper.rb
module CategoriaproductosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/preferidos_helper.rb
module PreferidosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tab_pages_helper.rb
module TabPagesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<%= link_to 'New Category', new_category_path %>

app/views/charts/index.html.erb
<div id="chart_div"></div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner" style="text-align: center;">
    <a class="logo" href="#" onclick="top.location = 'https://www.facebook.com/trendytamexico'">
    	<img src="http://www.trendyta.com/i/logo_trendyta.png"/>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>TrendytaPinTab</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header'%>
		<div class="container">
		<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/chart.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>TrendytaPinTab</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Producto');
        data.addColumn('number', 'Likes');
        data.addRows([
        	<%@likes.each do |l|%>
          ['<%=Product.find(l[0]).name%>', <%= l[1]%>],
          <%end%>
        ]);

        // Set chart options
        var options = {'title':'Likes a productos',
        				'is3D':true,
                       'width':600,
                       'height':600};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
	</head>
	<body>
		<%= render 'layouts/header'%>
		<div class="container">
		<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/redirect.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>TrendytaPinTab</title>
	</head>
	<body>
			<%= yield %>
	</body>
</html>

app/views/layouts/response.html.erb
<%=yield%>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id , Category.all.collect {|x| [x.name, x.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.image %></td>
    <td><%= Category.find(product.category_id).name %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Image:</b>
  <%= @product.image %>
</p>

<p>
  <b>Category:</b>
  <%= Category.find(@product.category_id).name %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<%= link_to 'New Product', new_product_path %>

app/views/session/_form.html.erb
<%= form_for(@user, url: '/signin') do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/session/login.html.erb
<%=render 'form'%>

app/views/session/signin.html.erb
<%=render 'form'%>

app/views/tab/index.html.erb
	<div class="rowtype1">
		<div class="row">
			<div class="span4">
				<%if @products.count > 0%>
				<a href="#" class="like-btn" id="<%= @products[0].id%>"> <div class="layover4 layover"></div>
				<div class="love-it4 love-it">
					Lo amo <i class="icon-heart icon-white"></i>
				</div> <img src="<%= @products[0].image%>" class="img-polaroid"> </a>
				<%end%>
			</div>
			<div class="span2">
				<div class="row">
					<div class="span2">
						
						<%if @products.count > 1%>
				<a href="#" class="like-btn" id="<%= @products[1].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[1].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span2">
						<%if @products.count > 2%>
				<a href="#" class="like-btn" id="<%= @products[2].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[2].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
			<div class="span2">
				<div class="row">
					<div class="span2">
						<%if @products.count > 3%>
				<a href="#" class="like-btn" id="<%= @products[3].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[3].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span2">
						<%if @products.count > 4%>
				<a href="#" class="like-btn" id="<%= @products[4].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[4].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
			<div class="span4">
				<%if @products.count > 5%>
				<a href="#" class="like-btn" id="<%= @products[5].id%>"> <div class="layover4 layover"></div>
				<div class="love-it4 love-it">
					Lo amo <i class="icon-heart icon-white"></i>
				</div> <img src="<%= @products[5].image%>" class="img-polaroid"> </a>
				<%end%>
			</div>
		</div>
	</div>

	<div class="rowtype5">
		<div class="row">
			<div class="span3">
				<div class="row">
					<div class="span3">
						<%if @products.count > 6%>
				<a href="#" class="like-btn" id="<%= @products[6].id%>"> <div class="layover3 layover"></div>
						<div class="love-it3 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[6].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span3">
						<%if @products.count > 7%>
				<a href="#" class="like-btn" id="<%= @products[7].id%>"> <div class="layover3 layover"></div>
						<div class="love-it3 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[7].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
			<div class="span6">
				<%if @products.count > 8%>
				<a href="#" class="like-btn" id="<%= @products[8].id%>"> <div class="layover6 layover"></div>
				<div class="love-it6 love-it">
					Lo amo <i class="icon-heart icon-white"></i>
				</div> <img src="<%= @products[8].image%>" class="img-polaroid"> </a>
				<%end%>
			</div>
			<div class="span3">
				<div class="row">
					<div class="span3">
						<%if @products.count > 9%>
				<a href="#" class="like-btn" id="<%= @products[9].id%>"> <div class="layover3 layover"></div>
						<div class="love-it3 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[9].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span3">
						<%if @products.count > 10%>
				<a href="#" class="like-btn" id="<%= @products[10].id%>"> <div class="layover3 layover"></div>
						<div class="love-it3 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[10].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="rowtype2">
		<div class="row">
			<div class="span2">
				<div class="row">
					<div class="span2">
						<%if @products.count > 11%>
				<a href="#" class="like-btn" id="<%= @products[11].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[11].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span2">
						<%if @products.count > 12%>
				<a href="#" class="like-btn" id="<%= @products[12].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[12].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
			<div class="span4">
				<%if @products.count > 13%>
				<a href="#" class="like-btn" id="<%= @products[13].id%>"> <div class="layover4 layover"></div>
				<div class="love-it4 love-it">
					Lo amo <i class="icon-heart icon-white"></i>
				</div> <img src="<%= @products[13].image%>" class="img-polaroid"> </a>
				<%end%>
			</div>
			<div class="span4">
				<%if @products.count > 14%>
				<a href="#" class="like-btn" id="<%= @products[14].id%>"> <div class="layover4 layover"></div>
				<div class="love-it4 love-it">
					Lo amo <i class="icon-heart icon-white"></i>
				</div> <img src="<%= @products[14].image%>" class="img-polaroid"> </a>
				<%end%>
			</div>
			<div class="span2">
				<div class="row">
					<div class="span2">
						<%if @products.count > 15%>
				<a href="#" class="like-btn" id="<%= @products[15].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[15].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span2">
						<%if @products.count > 16%>
				<a href="#" class="like-btn" id="<%= @products[16].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[16].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="rowtype6">
		<div class="row">
			<div class="span2">
				<div class="row">
					<div class="span2">
						<%if @products.count > 17%>
				<a href="#" class="like-btn" id="<%= @products[17].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[17].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span2">
						<%if @products.count > 18%>
				<a href="#" class="like-btn" id="<%= @products[18].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[18].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
			<div class="span2">
				<div class="row">
					<div class="span2">
						<%if @products.count > 19%>
				<a href="#" class="like-btn" id="<%= @products[19].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[19].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span2">
						<%if @products.count > 20%>
				<a href="#" class="like-btn" id="<%= @products[20].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[20].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
			<div class="span4">
				<%if @products.count > 21%>
				<a href="#" class="like-btn" id="<%= @products[21].id%>"> <div class="layover4 layover"></div>
				<div class="love-it4 love-it">
					Lo amo <i class="icon-heart icon-white"></i>
				</div> <img src="<%= @products[21].image%>" class="img-polaroid"> </a>
				<%end%>
			</div>
			<div class="span2">
				<div class="row">
					<div class="span2">
						<%if @products.count > 22%>
				<a href="#" class="like-btn" id="<%= @products[22].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[22].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span2">
						<%if @products.count > 23%>
				<a href="#" class="like-btn" id="<%= @products[23].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[23].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
			<div class="span2">
				<div class="row">
					<div class="span2">
						<%if @products.count > 24%>
				<a href="#" class="like-btn" id="<%= @products[24].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[24].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span2">
						<%if @products.count > 25%>
				<a href="#" class="like-btn" id="<%= @products[25].id%>"> <div class="layover2 layover"></div>
						<div class="love-it2 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[25].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="rowtype4">
		<div class="row">
			<div class="span6">
				<%if @products.count > 26%>
				<a href="#" class="like-btn" id="<%= @products[26].id%>"> <div class="layover6 layover"></div>
				<div class="love-it6 love-it">
					Lo amo <i class="icon-heart icon-white"></i>
				</div> <img src="<%= @products[26].image%>" class="img-polaroid"> </a>
				<%end%>
			</div>
			<div class="span3">
				<div class="row">
					<div class="span3">
						<%if @products.count > 27%>
				<a href="#" class="like-btn" id="<%= @products[27].id%>"> <div class="layover3 layover"></div>
						<div class="love-it3 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[27].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span3">
						<%if @products.count > 28%>
				<a href="#" class="like-btn" id="<%= @products[28].id%>"> <div class="layover3 layover"></div>
						<div class="love-it3 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[28].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
			<div class="span3">
				<div class="row">
					<div class="span3">
						<%if @products.count > 29%>
				<a href="#" class="like-btn" id="<%= @products[29].id%>"> <div class="layover3 layover"></div>
						<div class="love-it3 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[29].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
				<div class="row">
					<div class="span3">
						<%if @products.count > 30%>
				<a href="#" class="like-btn" id="<%= @products[30].id%>"> <div class="layover3 layover"></div>
						<div class="love-it3 love-it">
							Lo amo <i class="icon-heart icon-white"></i>
						</div> <img src="<%= @products[30].image%>" class="img-polaroid"> </a>
				<%end%>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/tab/login.html.erb
<script>
	top.location = 'https://www.facebook.com/dialog/oauth?client_id=542124329158664&redirect_uri=https://dev-machine.com:3000/tab/';
</script>

app/views/tab/redirect_app.html.erb
<script>
	top.location = 'http://apps.facebook.com/trendyta_pins';
</script>